spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysq://projecttt-databse-deploy.cpj1bduzsphj.ap-northeast-2.rds.amazonaws.com:13306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: projecttt32
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    domain: http://projecttt-client-bucket.s3-website.ap-northeast-2.amazonaws.com/